-- Lavet af: OMikkel#3217
-- Script: omik_attachments
Config = {}

Config.hotkey = {true, 38} -- E {Hotkey aktiveret true/false, hotkeyknap https://docs.fivem.net/docs/game-references/controls/}

Config.reach = 1.5
Config.visible = 100.0

Config.hovertext = "Tryk [~g~E~w~] for at åbne attachment menuen for ~r~"

Config.locations = {
    {461.08023071289,-982.30853271484,30.689308166504, 27, 102, 178, 255},
    {1842.0380859375,3689.2719726563,34.286598205566, 27, 102, 178, 255}
}

Config.attachments = {
    --PISTOLS--
    ["-656458692"] = { --weapon_knuckle
        {"Base Model", "COMPONENT_KNUCKLE_VARMOD_BASE"},
        {"The Pimp", "COMPONENT_KNUCKLE_VARMOD_PIMP"},
        {"The Ballas", "COMPONENT_KNUCKLE_VARMOD_BALLAS"},
        {"The Hustler", "COMPONENT_KNUCKLE_VARMOD_DOLLAR"},
        {"The Rock", "COMPONENT_KNUCKLE_VARMOD_DIAMOND"},
        {"The Hater", "COMPONENT_KNUCKLE_VARMOD_HATE"},
        {"The Lover", "COMPONENT_KNUCKLE_VARMOD_LOVE"},
        {"The Player", "COMPONENT_KNUCKLE_VARMOD_PLAYER"},
        {"The King", "COMPONENT_KNUCKLE_VARMOD_KING"},
        {"The Vagos", "COMPONENT_KNUCKLE_VARMOD_VAGOS"}
    },
    ["-538741184"] = { --weapon_switchblade
        {"Base Model", "COMPONENT_SWITCHBLADE_VARMOD_BASE"},
        {"VIP Variant", "COMPONENT_SWITCHBLADE_VARMOD_VAR1"},
        {"Bodyguard Variant", "COMPONENT_SWITCHBLADE_VARMOD_VAR2"}
    },
    ["453432689"] = { --weapon_pistol
        {"Default Clip", "COMPONENT_PISTOL_CLIP_01"},
        {"Extended Clip", "COMPONENT_PISTOL_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP_02"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_PISTOL_VARMOD_LUXE"}
    },
    ["1593441988"] = { --weapon_combatpistol
        {"Default Clip", "COMPONENT_COMBATPISTOL_CLIP_01"},
        {"Extended Clip", "COMPONENT_COMBATPISTOL_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_COMBATPISTOL_VARMOD_LOWRIDER"}
    },
    ["584646201"] = { --weapon_appistol
        {"Default Clip", "COMPONENT_APPISTOL_CLIP_01"},
        {"Extended Clip", "COMPONENT_APPISTOL_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP"},
        {"Gilded Gun Metal Finish", "COMPONENT_APPISTOL_VARMOD_LUXE"}
    },
    ["-1716589765"] = { --weapon_pistol50
        {"Default Clip", "COMPONENT_PISTOL50_CLIP_01"},
        {"Extended Clip", "COMPONENT_PISTOL50_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Platinum Pearl Deluxe Finish", "COMPONENT_PISTOL50_VARMOD_LUXE"}
    },
    ["-1045183535"] = { --weapon_revolver
        {"Default Clip", "COMPONENT_REVOLVER_CLIP_01"},
        {"VIP Variant", "COMPONENT_REVOLVER_VARMOD_BOSS"},
        {"Bodyguard Variant", "COMPONENT_REVOLVER_VARMOD_GOON"}
    },
    ["-1076751822"] = { --weapon_snspistol
        {"Default Clip", "COMPONENT_SNSPISTOL_CLIP_01"},
        {"Extended Clip", "COMPONENT_SNSPISTOL_CLIP_02"},
        {"Etched Wood Grip Finish", "COMPONENT_SNSPISTOL_VARMOD_LOWRIDER"}
    },
    ["-771403250"] = { --weapon_heavypistol
        {"Default Clip", "COMPONENT_HEAVYPISTOL_CLIP_01"},
        {"Extended Clip", "COMPONENT_HEAVYPISTOL_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP"},
        {"Etched Wood Grip Finish", "COMPONENT_HEAVYPISTOL_VARMOD_LUXE"}
    },
    ["-879347409"] = { --weapon_revolver_mk2
        {"Default Rounds", "COMPONENT_REVOLVER_MK2_CLIP_01"},
        {"Tracer Rounds", "COMPONENT_REVOLVER_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_REVOLVER_MK2_CLIP_INCENDIARY"},
        {"Hollow Point Rounds", "COMPONENT_REVOLVER_MK2_CLIP_HOLLOWPOINT"},
        {"Full Metal Jacket Rounds", "COMPONENT_REVOLVER_MK2_CLIP_FMJ"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS"},
        {"Small Scope", "COMPONENT_AT_SCOPE_MACRO_MK2"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH"},
        {"Compensator", "COMPONENT_AT_PI_COMP_03"},
        {"Digital Camo", "COMPONENT_REVOLVER_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_REVOLVER_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_REVOLVER_MK2_CAMO_03"},
        {"Skull", "COMPONENT_REVOLVER_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_REVOLVER_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_REVOLVER_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_REVOLVER_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_REVOLVER_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_REVOLVER_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_REVOLVER_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_REVOLVER_MK2_CAMO_IND_01"}
    },
    ["-2009644972"] = { --weapon_snspistol_mk2
        {"Default Clip", "COMPONENT_SNSPISTOL_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_SNSPISTOL_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_SNSPISTOL_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_SNSPISTOL_MK2_CLIP_INCENDIARY"},
        {"Hollow Point Rounds", "COMPONENT_SNSPISTOL_MK2_CLIP_HOLLOWPOINT"},
        {"Full Metal Jacket Rounds", "COMPONENT_SNSPISTOL_MK2_CLIP_FMJ"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH_03"},
        {"Mounted Scope", "COMPONENT_AT_PI_RAIL_02"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP_02"},
        {"Compensator", "COMPONENT_AT_PI_COMP_02"},
        {"Digital Camo", "COMPONENT_SNSPISTOL_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_SNSPISTOL_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_SNSPISTOL_MK2_CAMO_03"},
        {"Skull", "COMPONENT_SNSPISTOL_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_SNSPISTOL_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_SNSPISTOL_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_SNSPISTOL_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_SNSPISTOL_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_SNSPISTOL_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_SNSPISTOL_MK2_CAMO_10"},
        {"Boom! 2", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01"},
        {"Digital Camo 2", "COMPONENT_SNSPISTOL_MK2_CAMO_SLIDE"},
        {"Brushstroke Camo 2", "COMPONENT_SNSPISTOL_MK2_CAMO_02_SLIDE"},
        {"Woodland Camo	2", "COMPONENT_SNSPISTOL_MK2_CAMO_03_SLIDE"},
        {"Skull	2", "COMPONENT_SNSPISTOL_MK2_CAMO_04_SLIDE"},
        {"Sessanta Nove	2", "COMPONENT_SNSPISTOL_MK2_CAMO_05_SLIDE"},
        {"Perseus 2", "COMPONENT_SNSPISTOL_MK2_CAMO_06_SLIDE"},
        {"Leopard 2", "COMPONENT_SNSPISTOL_MK2_CAMO_07_SLIDE"},
        {"Zebra 2", "COMPONENT_SNSPISTOL_MK2_CAMO_08_SLIDE"},
        {"Geometric 2", "COMPONENT_SNSPISTOL_MK2_CAMO_09_SLIDE"},
        {"Boom! 2", "COMPONENT_SNSPISTOL_MK2_CAMO_10_SLIDE"},
        {"Patriotic 2", "COMPONENT_SNSPISTOL_MK2_CAMO_IND_01_SLIDE"}
    },
    ["-1075685676"] = { --weapon_pistol_mk2
        {"Default Clip", "COMPONENT_PISTOL_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_PISTOL_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_PISTOL_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_PISTOL_MK2_CLIP_INCENDIARY"},
        {"Hollow Point Rounds", "COMPONENT_PISTOL_MK2_CLIP_HOLLOWPOINT"},
        {"Full Metal Jacket Rounds", "COMPONENT_PISTOL_MK2_CLIP_FMJ"},
        {"Mounted Scope", "COMPONENT_AT_PI_RAIL"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH_02"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP_02"},
        {"Compensator", "COMPONENT_AT_PI_COMP"},
        {"Digital Camo", "COMPONENT_PISTOL_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_PISTOL_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_PISTOL_MK2_CAMO_03"},
        {"Skull", "COMPONENT_PISTOL_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_PISTOL_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_PISTOL_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_PISTOL_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_PISTOL_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_PISTOL_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_PISTOL_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_PISTOL_MK2_CAMO_IND_01"},
        {"Digital Camo 2", "COMPONENT_PISTOL_MK2_CAMO_SLIDE"},
        {"Digital Camo 3", "COMPONENT_PISTOL_MK2_CAMO_02_SLIDE"},
        {"Digital Camo 4", "COMPONENT_PISTOL_MK2_CAMO_03_SLIDE"},
        {"Digital Camo 5", "COMPONENT_PISTOL_MK2_CAMO_04_SLIDE"},
        {"Digital Camo 6", "COMPONENT_PISTOL_MK2_CAMO_05_SLIDE"},
        {"Digital Camo 7", "COMPONENT_PISTOL_MK2_CAMO_06_SLIDE"},
        {"Digital Camo 8", "COMPONENT_PISTOL_MK2_CAMO_07_SLIDE"},
        {"Digital Camo 9", "COMPONENT_PISTOL_MK2_CAMO_08_SLIDE"},
        {"Digital Camo 10", "COMPONENT_PISTOL_MK2_CAMO_09_SLIDE"},
        {"Digital Camo 11", "COMPONENT_PISTOL_MK2_CAMO_10_SLIDE"},
        {"Patriotic 2", "COMPONENT_PISTOL_MK2_CAMO_IND_01_SLIDE"}
    },
    ["137902532"] = { --weapon_vintagepistol
        {"Default Clip", "COMPONENT_VINTAGEPISTOL_CLIP_01"},
        {"Extended Clip", "COMPONENT_VINTAGEPISTOL_CLIP_02"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP"}
    },
    ["-1355376991"] = { --weapon_raypistol
        {"Festive tint", "COMPONENT_RAYPISTOL_VARMOD_XMAS18"}
    },
    ["727643628"] = { --weapon_ceramicpistol
        {"Default Clip", "COMPONENT_CERAMICPISTOL_CLIP_01"},
        {"Extended Clip", "COMPONENT_CERAMICPISTOL_CLIP_02"},
        {"Suppressor", "COMPONENT_CERAMICPISTOL_SUPP"}
    },

    --SMGS--
    ["324215364"] = { --weapon_microsmg
        {"Default Clip", "COMPONENT_MICROSMG_CLIP_01"},
        {"Extended Clip", "COMPONENT_MICROSMG_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_PI_FLSH"},
        {"Scope", "COMPONENT_AT_SCOPE_MACRO"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_MICROSMG_VARMOD_LUXE"}
    },
    ["736523883"] = { --weapon_smg
        {"Default Clip", "COMPONENT_SMG_CLIP_01"},
        {"Extended Clip", "COMPONENT_SMG_CLIP_02"},
        {"Drum Magazine", "COMPONENT_SMG_CLIP_03"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Scope", "COMPONENT_AT_SCOPE_MACRO_02"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_SMG_VARMOD_LUXE"}
    },
    ["-270015777"] = { --weapon_assaultsmg
        {"Default Clip", "COMPONENT_ASSAULTSMG_CLIP_01"},
        {"Extended Clip", "COMPONENT_ASSAULTSMG_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Scope", "COMPONENT_AT_SCOPE_MACRO"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_ASSAULTSMG_VARMOD_LOWRIDER"}
    },
    ["-1121678507"] = { --weapon_minismg
        {"Default Clip", "COMPONENT_MINISMG_CLIP_01"},
        {"Extended Clip", "COMPONENT_MINISMG_CLIP_02"}
    },
    ["2024373456"] = { --weapon_smg_mk2
        {"Default Clip", "COMPONENT_SMG_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_SMG_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_SMG_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_SMG_MK2_CLIP_INCENDIARY"},
        {"Hollow Point Rounds", "COMPONENT_SMG_MK2_CLIP_HOLLOWPOINT"},
        {"Full Metal Jacket Rounds", "COMPONENT_SMG_MK2_CLIP_FMJ"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS_SMG"},
        {"Small Scope", "COMPONENT_AT_SCOPE_MACRO_02_SMG_MK2"},
        {"Medium Scope", "COMPONENT_AT_SCOPE_SMALL_SMG_MK2"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP"},
        {"Flat Muzzle Brake", "COMPONENT_AT_MUZZLE_01"},
        {"Tactical Muzzle Brake", "COMPONENT_AT_MUZZLE_02"},
        {"Fat-End Muzzle Brake", "COMPONENT_AT_MUZZLE_03"},
        {"Precision Muzzle Brake", "COMPONENT_AT_MUZZLE_04"},
        {"Heavy Duty Muzzle Brake", "COMPONENT_AT_MUZZLE_05"},
        {"Slanted Muzzle Brake", "COMPONENT_AT_MUZZLE_06"},
        {"Split-End Muzzle Brake", "COMPONENT_AT_MUZZLE_07"},
        {"Default Barrel", "COMPONENT_AT_SB_BARREL_01"},
        {"Heavy Barrel", "COMPONENT_AT_SB_BARREL_02"},
        {"Digital Camo", "COMPONENT_SMG_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_SMG_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_SMG_MK2_CAMO_03"},
        {"Skull", "COMPONENT_SMG_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_SMG_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_SMG_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_SMG_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_SMG_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_SMG_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_SMG_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_SMG_MK2_CAMO_IND_01"},
    },
    ["-619010992"] = { --weapon_machinepistol
        {"Default Clip", "COMPONENT_MACHINEPISTOL_CLIP_01"},
        {"Extended Clip", "COMPONENT_MACHINEPISTOL_CLIP_02"},
        {"Drum Magazine", "COMPONENT_MACHINEPISTOL_CLIP_03"},
        {"Suppressor", "COMPONENT_AT_PI_SUPP"}
    },
    ["171789620"] = { --weapon_combatpdw
        {"Default Clip", "COMPONENT_COMBATPDW_CLIP_01"},
        {"Extended Clip", "COMPONENT_COMBATPDW_CLIP_02"},
        {"Drum Magazine", "COMPONENT_COMBATPDW_CLIP_03"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"},
        {"Scope", "COMPONENT_AT_SCOPE_SMALL"}
    },

    --SHOTGUNS--
    ["487013001"] = { --weapon_pumpshotgun
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Suppressor", "COMPONENT_AT_SR_SUPP"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_PUMPSHOTGUN_VARMOD_LOWRIDER"}
    },
    ["2017895192"] = { --weapon_sawnoffshotgun
        {"Gilded Gun Metal Finish", "COMPONENT_SAWNOFFSHOTGUN_VARMOD_LUXE"}
    },
    ["-494615257"] = { --weapon_assaultshotgun
        {"Default Clip", "COMPONENT_ASSAULTSHOTGUN_CLIP_01"},
        {"Extended Clip", "COMPONENT_ASSAULTSHOTGUN_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"}
    },
    ["-1654528753"] = { --weapon_bullpupshotgun
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"}
    },
    ["1432025498"] = { --weapon_pumpshotgun_mk2
        {"Default Shells", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_01"},
        {"Dragon's Breath Shells", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_INCENDIARY"},
        {"Steel Buckshot Shells", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_ARMORPIERCING"},
        {"Flechette Shells", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_HOLLOWPOINT"},
        {"Explosive Slugs", "COMPONENT_PUMPSHOTGUN_MK2_CLIP_EXPLOSIVE"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS"},
        {"Small Scope", "COMPONENT_AT_SCOPE_MACRO_MK2"},
        {"Medium Scope", "COMPONENT_AT_SCOPE_SMALL_MK2"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Suppressor", "COMPONENT_AT_SR_SUPP_03"},
        {"Squared Muzzle Brake", "COMPONENT_AT_MUZZLE_08"},
        {"Digital Camo", "COMPONENT_PUMPSHOTGUN_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_03"},
        {"Skull", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_PUMPSHOTGUN_MK2_CAMO_IND_01"},
    },
    ["984333226"] = { --weapon_heavyshotgun
        {"Default Clip", "COMPONENT_HEAVYSHOTGUN_CLIP_01"},
        {"Extended Clip", "COMPONENT_HEAVYSHOTGUN_CLIP_02"},
        {"Drum Magazine", "COMPONENT_HEAVYSHOTGUN_CLIP_03"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"}
    },

    --RIFLES--
    ["-1074790547"] = { --weapon_assaultrifle
        {"Default Clip", "COMPONENT_ASSAULTRIFLE_CLIP_01"},
        {"Extended Clip", "COMPONENT_ASSAULTRIFLE_CLIP_02"},
        {"Drum Magazine", "COMPONENT_ASSAULTRIFLE_CLIP_03"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Scope", "COMPONENT_AT_SCOPE_MACRO"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_ASSAULTRIFLE_VARMOD_LUXE"}
    },
    ["-2084633992"] = { --weapon_carbinerifle
        {"Default Clip", "COMPONENT_CARBINERIFLE_CLIP_01"},
        {"Extended Clip", "COMPONENT_CARBINERIFLE_CLIP_02"},
        {"Box Magazine", "COMPONENT_CARBINERIFLE_CLIP_03"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Scope", "COMPONENT_AT_SCOPE_MEDIUM"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_CARBINERIFLE_VARMOD_LUXE"}
    },
    ["-1357824103"] = { --weapon_advancedrifle
        {"Default Clip", "COMPONENT_ADVANCEDRIFLE_CLIP_01"},
        {"Extended Clip", "COMPONENT_ADVANCEDRIFLE_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Scope", "COMPONENT_AT_SCOPE_SMALL"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP"},
        {"Gilded Gun Metal Finish", "COMPONENT_ADVANCEDRIFLE_VARMOD_LUXE"}
    },
    ["-1063057011"] = { --weapon_specialcarbine
        {"Default Clip", "COMPONENT_SPECIALCARBINE_CLIP_01"},
        {"Extended Clip", "COMPONENT_SPECIALCARBINE_CLIP_02"},
        {"Drum Magazine", "COMPONENT_SPECIALCARBINE_CLIP_03"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Scope", "COMPONENT_AT_SCOPE_MEDIUM"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"},
        {"Etched Gun Metal Finish", "COMPONENT_SPECIALCARBINE_VARMOD_LOWRIDER"}
    },
    ["2132975508"] = { --weapon_bullpuprifle
        {"Default Clip", "COMPONENT_BULLPUPRIFLE_CLIP_01"},
        {"Extended Clip", "COMPONENT_BULLPUPRIFLE_CLIP_02"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Scope", "COMPONENT_AT_SCOPE_SMALL"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"},
        {"Gilded Gun Metal Finish", "COMPONENT_BULLPUPRIFLE_VARMOD_LOWRIDER"}
    },
    ["-2066285827"] = { --weapon_bullpuprifle_mk2
        {"Default Clip", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_INCENDIARY"},
        {"Armor Piercing Rounds", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_ARMORPIERCING"},
        {"Full Metal Jacket Rounds", "COMPONENT_BULLPUPRIFLE_MK2_CLIP_FMJ"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS"},
        {"Small Scope", "COMPONENT_AT_SCOPE_MACRO_02_MK2"},
        {"Medium Scope", "COMPONENT_AT_SCOPE_SMALL_MK2"},
        {"Default Barrel", "COMPONENT_AT_BP_BARREL_01"},
        {"Heavy Barrel", "COMPONENT_AT_BP_BARREL_02"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP"},
        {"Flat Muzzle Brake", "COMPONENT_AT_MUZZLE_01"},
        {"Tactical Muzzle Brake", "COMPONENT_AT_MUZZLE_02"},
        {"Fat-End Muzzle Brake", "COMPONENT_AT_MUZZLE_03"},
        {"Precision Muzzle Brake", "COMPONENT_AT_MUZZLE_04"},
        {"Heavy Duty Muzzle Brake", "COMPONENT_AT_MUZZLE_05"},
        {"Slanted Muzzle Brake", "COMPONENT_AT_MUZZLE_06"},
        {"Split-End Muzzle Brake", "COMPONENT_AT_MUZZLE_07"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP_02"},
        {"Digital Camo", "COMPONENT_BULLPUPRIFLE_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_03"},
        {"Skull", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_BULLPUPRIFLE_MK2_CAMO_IND_01"},
    },
    ["-1768145561"] = { --weapon_specialcarbine_mk2
        {"Default Clip", "COMPONENT_SPECIALCARBINE_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_SPECIALCARBINE_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_SPECIALCARBINE_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_SPECIALCARBINE_MK2_CLIP_INCENDIARY"},
        {"Armor Piercing Rounds", "COMPONENT_SPECIALCARBINE_MK2_CLIP_ARMORPIERCING"},
        {"Full Metal Jacket Rounds", "COMPONENT_SPECIALCARBINE_MK2_CLIP_FMJ"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS"},
        {"Small Scope", "COMPONENT_AT_SCOPE_MACRO_MK2"},
        {"Large Scope", "COMPONENT_AT_SCOPE_MEDIUM_MK2"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Flat Muzzle Brake", "COMPONENT_AT_MUZZLE_01"},
        {"Tactical Muzzle Brake", "COMPONENT_AT_MUZZLE_02"},
        {"Fat-End Muzzle Brake", "COMPONENT_AT_MUZZLE_03"},
        {"Precision Muzzle Brake", "COMPONENT_AT_MUZZLE_04"},
        {"Heavy Duty Muzzle Brake", "COMPONENT_AT_MUZZLE_05"},
        {"Slanted Muzzle Brake", "COMPONENT_AT_MUZZLE_06"},
        {"Split-End Muzzle Brake", "COMPONENT_AT_MUZZLE_07"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP_02"},
        {"Default Barrel", "COMPONENT_AT_SC_BARREL_01"},
        {"Heavy Barrel", "COMPONENT_AT_SC_BARREL_02"},
        {"Digital Camo", "COMPONENT_SPECIALCARBINE_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_SPECIALCARBINE_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_SPECIALCARBINE_MK2_CAMO_03"},
        {"Skull", "COMPONENT_SPECIALCARBINE_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_SPECIALCARBINE_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_SPECIALCARBINE_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_SPECIALCARBINE_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_SPECIALCARBINE_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_SPECIALCARBINE_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_SPECIALCARBINE_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_SPECIALCARBINE_MK2_CAMO_IND_01"},
    },
    ["961495388"] = { --weapon_assaultrifle_mk2
        {"Default Clip", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_INCENDIARY"},
        {"Armor Piercing Rounds", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_ARMORPIERCING"},
        {"Full Metal Jacket Rounds", "COMPONENT_ASSAULTRIFLE_MK2_CLIP_FMJ"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP_02"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS"},
        {"Small Scope", "COMPONENT_AT_SCOPE_MACRO_MK2"},
        {"Large Scope", "COMPONENT_AT_SCOPE_MEDIUM_MK2"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Flat Muzzle Brake", "COMPONENT_AT_MUZZLE_01"},
        {"Tactical Muzzle Brake", "COMPONENT_AT_MUZZLE_02"},
        {"Fat-End Muzzle Brake", "COMPONENT_AT_MUZZLE_03"},
        {"Precision Muzzle Brake", "COMPONENT_AT_MUZZLE_04"},
        {"Heavy Duty Muzzle Brake", "COMPONENT_AT_MUZZLE_05"},
        {"Slanted Muzzle Brake", "COMPONENT_AT_MUZZLE_06"},
        {"Split-End Muzzle Brake", "COMPONENT_AT_MUZZLE_07"},
        {"Default Barrel", "COMPONENT_AT_AR_BARREL_01"},
        {"Heavy Barrel", "COMPONENT_AT_AR_BARREL_02"},
        {"Digital Camo", "COMPONENT_ASSAULTRIFLE_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_03"},
        {"Skull", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_ASSAULTRIFLE_MK2_CAMO_IND_01"},
    },
    ["-86904375"] = { --weapon_carbinerifle_mk2
        {"Default Clip", "COMPONENT_CARBINERIFLE_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_CARBINERIFLE_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_CARBINERIFLE_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_CARBINERIFLE_MK2_CLIP_INCENDIARY"},
        {"Armor Piercing Rounds", "COMPONENT_CARBINERIFLE_MK2_CLIP_ARMORPIERCING"},
        {"Full Metal Jacket Rounds", "COMPONENT_CARBINERIFLE_MK2_CLIP_FMJ"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP_02"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS"},
        {"Small Scope", "COMPONENT_AT_SCOPE_MACRO_MK2"},
        {"Large Scope", "COMPONENT_AT_SCOPE_MEDIUM_MK2"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP"},
        {"Flat Muzzle Brake", "COMPONENT_AT_MUZZLE_01"},
        {"Tactical Muzzle Brake", "COMPONENT_AT_MUZZLE_02"},
        {"Fat-End Muzzle Brake", "COMPONENT_AT_MUZZLE_03"},
        {"Precision Muzzle Brake", "COMPONENT_AT_MUZZLE_04"},
        {"Heavy Duty Muzzle Brake", "COMPONENT_AT_MUZZLE_05"},
        {"Slanted Muzzle Brake", "COMPONENT_AT_MUZZLE_06"},
        {"Split-End Muzzle Brake", "COMPONENT_AT_MUZZLE_07"},
        {"Default Barrel", "COMPONENT_AT_CR_BARREL_01"},
        {"Heavy Barrel", "COMPONENT_AT_CR_BARREL_02"},
        {"Digital Camo", "COMPONENT_CARBINERIFLE_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_CARBINERIFLE_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_CARBINERIFLE_MK2_CAMO_03"},
        {"Skull", "COMPONENT_CARBINERIFLE_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_CARBINERIFLE_MK2_CAMO_05	"},
        {"Perseus", "COMPONENT_CARBINERIFLE_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_CARBINERIFLE_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_CARBINERIFLE_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_CARBINERIFLE_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_CARBINERIFLE_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_CARBINERIFLE_MK2_CAMO_IND_01"},
    },
    ["1649403952"] = { --weapon_compactrifle
        {"Default Clip", "COMPONENT_COMPACTRIFLE_CLIP_01"},
        {"Extended Clip", "COMPONENT_COMPACTRIFLE_CLIP_02"},
        {"Drum Magazine", "COMPONENT_COMPACTRIFLE_CLIP_03"}
    },

    --RIFLES--
    ["-1660422300"] = { --weapon_mg
        {"Default Clip", "COMPONENT_MG_CLIP_01"},
        {"Extended Clip", "COMPONENT_MG_CLIP_02"},
        {"Scope", "COMPONENT_AT_SCOPE_SMALL_02"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_MG_VARMOD_LOWRIDER"}
    },
    ["2144741730"] = { --weapon_combatmg
        {"Default Clip", "COMPONENT_COMBATMG_CLIP_01"},
        {"Extended Clip", "COMPONENT_COMBATMG_CLIP_02"},
        {"Scope", "COMPONENT_AT_SCOPE_MEDIUM"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"},
        {"Etched Gun Metal Finish", "COMPONENT_COMBATMG_VARMOD_LOWRIDER"}
    },
    ["3686625920"] = { --weapon_combatmg_mk2
        {"Default Clip", "COMPONENT_COMBATMG_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_COMBATMG_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_COMBATMG_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_COMBATMG_MK2_CLIP_INCENDIARY"},
        {"Armor Piercing Rounds", "COMPONENT_COMBATMG_MK2_CLIP_ARMORPIERCING"},
        {"Full Metal Jacket Rounds", "COMPONENT_COMBATMG_MK2_CLIP_FMJ"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP_02"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS"},
        {"Medium Scope", "COMPONENT_AT_SCOPE_SMALL_MK2"},
        {"Large Scope", "COMPONENT_AT_SCOPE_MEDIUM_MK2"},
        {"Flat Muzzle Brake", "COMPONENT_AT_MUZZLE_01"},
        {"Tactical Muzzle Brake", "COMPONENT_AT_MUZZLE_02"},
        {"Fat-End Muzzle Brake", "COMPONENT_AT_MUZZLE_03"},
        {"Precision Muzzle Brake", "COMPONENT_AT_MUZZLE_04"},
        {"Heavy Duty Muzzle Brake", "COMPONENT_AT_MUZZLE_05"},
        {"Slanted Muzzle Brake", "COMPONENT_AT_MUZZLE_06"},
        {"Split-End Muzzle Brake", "COMPONENT_AT_MUZZLE_07"},
        {"Default Barrel", "COMPONENT_AT_MG_BARREL_01"},
        {"Heavy Barrel", "COMPONENT_AT_MG_BARREL_02"},
        {"Digital Camo", "COMPONENT_COMBATMG_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_COMBATMG_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_COMBATMG_MK2_CAMO_03"},
        {"Skull", "COMPONENT_COMBATMG_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_COMBATMG_MK2_CAMO_05	"},
        {"Perseus", "COMPONENT_COMBATMG_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_COMBATMG_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_COMBATMG_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_COMBATMG_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_COMBATMG_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_COMBATMG_MK2_CAMO_IND_01"},
    },
    ["1627465347"] = { --weapon_gusenberg
        {"Default Clip", "COMPONENT_GUSENBERG_CLIP_01"},
        {"Extended Clip", "COMPONENT_GUSENBERG_CLIP_02"}
    },

    --SNIPER RIFLES--
    ["100416529"] = { --weapon_sniperrifle
        {"Default Clip", "COMPONENT_SNIPERRIFLE_CLIP_01"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP_02"},
        {"Scope", "COMPONENT_AT_SCOPE_LARGE"},
        {"Advanced Scope", "COMPONENT_AT_SCOPE_MAX"},
        {"Etched Wood Grip Finish", "COMPONENT_SNIPERRIFLE_VARMOD_LUXE"}
    },
    ["205991906"] = { --weapon_heavysniper
        {"Default Clip", "COMPONENT_HEAVYSNIPER_CLIP_01"},
        {"Scope", "COMPONENT_AT_SCOPE_LARGE"},
        {"Advanced Scope", "COMPONENT_AT_SCOPE_MAX"}
    },
    ["1785463520"] = { --weapon_marksmanrifle_mk2
        {"Default Clip", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_02"},
        {"Tracer Rounds", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_TRACER"},
        {"Incendiary Rounds", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_INCENDIARY"},
        {"Armor Piercing Rounds", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_ARMORPIERCING"},
        {"Full Metal Jacket Rounds", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ"},
        {"Holographic Sight", "COMPONENT_AT_SIGHTS"},
        {"Large Scope", "COMPONENT_AT_SCOPE_MEDIUM_MK2"},
        {"Zoom Scope", "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM_MK2"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP"},
        {"Flat Muzzle Brake", "COMPONENT_AT_MUZZLE_01"},
        {"Tactical Muzzle Brake", "COMPONENT_AT_MUZZLE_02"},
        {"Fat-End Muzzle Brake", "COMPONENT_AT_MUZZLE_03"},
        {"Precision Muzzle Brake", "COMPONENT_AT_MUZZLE_04"},
        {"Heavy Duty Muzzle Brake", "COMPONENT_AT_MUZZLE_05"},
        {"Slanted Muzzle Brake", "COMPONENT_AT_MUZZLE_06"},
        {"Split-End Muzzle Brake", "COMPONENT_AT_MUZZLE_07"},
        {"Default Barrel", "COMPONENT_AT_MRFL_BARREL_01"},
        {"Heavy Barrel", "COMPONENT_AT_MRFL_BARREL_02"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP_02"},
        {"Digital Camo", "COMPONENT_MARKSMANRIFLE_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_03"},
        {"Skull", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_10"},
        {"Boom! 2", "COMPONENT_MARKSMANRIFLE_MK2_CAMO_IND_01"},
    },
    ["177293209"] = { --weapon_heavysniper_mk2
        {"Default Clip", "COMPONENT_HEAVYSNIPER_MK2_CLIP_01"},
        {"Extended Clip", "COMPONENT_HEAVYSNIPER_MK2_CLIP_02"},
        {"Incendiary Rounds", "COMPONENT_HEAVYSNIPER_MK2_CLIP_INCENDIARY"},
        {"Armor Piercing Rounds", "COMPONENT_HEAVYSNIPER_MK2_CLIP_ARMORPIERCING"},
        {"Full Metal Jacket Rounds", "COMPONENT_HEAVYSNIPER_MK2_CLIP_FMJ"},
        {"Explosive Rounds", "COMPONENT_HEAVYSNIPER_MK2_CLIP_EXPLOSIVE"},
        {"Zoom Scope", "COMPONENT_AT_SCOPE_LARGE_MK2"},
        {"Advanced Scope", "COMPONENT_AT_SCOPE_MAX"},
        {"Night Vision Scope", "COMPONENT_AT_SCOPE_NV"},
        {"Thermal Scope", "COMPONENT_AT_SCOPE_THERMAL"},
        {"Suppressor", "COMPONENT_AT_SR_SUPP_03"},
        {"Squared Muzzle Brake", "COMPONENT_AT_MUZZLE_08"},
        {"Bell-End Muzzle Brake", "COMPONENT_AT_MUZZLE_09"},
        {"Default Barrel", "COMPONENT_AT_SR_BARREL_01"},
        {"Heavy Barrel", "COMPONENT_AT_SR_BARREL_02"},
        {"Digital Camo", "COMPONENT_HEAVYSNIPER_MK2_CAMO"},
        {"Brushstroke Camo", "COMPONENT_HEAVYSNIPER_MK2_CAMO_02"},
        {"Woodland Camo", "COMPONENT_HEAVYSNIPER_MK2_CAMO_03"},
        {"Skull", "COMPONENT_HEAVYSNIPER_MK2_CAMO_04"},
        {"Sessanta Nove", "COMPONENT_HEAVYSNIPER_MK2_CAMO_05"},
        {"Perseus", "COMPONENT_HEAVYSNIPER_MK2_CAMO_06"},
        {"Leopard", "COMPONENT_HEAVYSNIPER_MK2_CAMO_07"},
        {"Zebra", "COMPONENT_HEAVYSNIPER_MK2_CAMO_08"},
        {"Geometric", "COMPONENT_HEAVYSNIPER_MK2_CAMO_09"},
        {"Boom!", "COMPONENT_HEAVYSNIPER_MK2_CAMO_10"},
        {"Patriotic", "COMPONENT_HEAVYSNIPER_MK2_CAMO_IND_01"},
    },
    ["-952879014"] = { --weapon_marksmanrifle
        {"Default Clip", "COMPONENT_MARKSMANRIFLE_CLIP_01"},
        {"Extended Clip", "COMPONENT_MARKSMANRIFLE_CLIP_02"},
        {"Scope", "COMPONENT_AT_SCOPE_LARGE_FIXED_ZOOM"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Suppressor", "COMPONENT_AT_AR_SUPP"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"},
        {"Yusuf Amir Luxury Finish", "COMPONENT_MARKSMANRIFLE_VARMOD_LUXE"},
    },

    --HEAVY WEAPONS--
    ["-1568386805"] = { --weapon_grenadelauncher
        {"Default Clip", "COMPONENT_GRENADELAUNCHER_CLIP_01"},
        {"Flashlight", "COMPONENT_AT_AR_FLSH"},
        {"Grip", "COMPONENT_AT_AR_AFGRIP"},
        {"Scope", "COMPONENT_AT_SCOPE_SMALL"}
    },
}

Config.weapons = {
    --PISTOLS--
    ["-656458692"] = {"Knojern","https://i.imgur.com/TTjiJXs.png"},
    ["-538741184"] = {"Lommekniv","https://i.imgur.com/azXxohi.png"},
    ["453432689"] = {"Pistol","https://i.imgur.com/gBj94Ji.png"},
    ["1593441988"] = {"Combat Pistol","https://i.imgur.com/Xw7v40x.png"},
    ["584646201"] = {"AP Pistol","https://i.imgur.com/XDMh5mX.png"},
    ["-1716589765"] = {"Pistol 50","https://i.imgur.com/Qp4nLk4.png"},
    ["-1045183535"] = {"Revolver","https://i.imgur.com/f26ypnx.png"},
    ["-1076751822"] = {"SNS Pistol","https://i.imgur.com/Z4orOfm.png"},
    ["-771403250"] = {"Heavy Pistol","https://i.imgur.com/8WbqM1N.png"},
    ["-879347409"] = {"Revolver MK2","https://i.imgur.com/HSxudK0.png"},
    ["-2009644972"] = {"SNS Pistol MK2","https://i.imgur.com/e0oGb5w.png"},
    ["-1075685676"] = {"Pistol MK2","https://i.imgur.com/hAvNpf2.png"},
    ["137902532"] = {"Vintage Pistol","https://i.imgur.com/RkL9ksH.png"},
    ["-1355376991"] = {"Ray Pistol","https://i.imgur.com/M07rWxZ.png"},
    ["727643628"] = {"Ceramic Pistol","https://i.imgur.com/oPAAWDZ.png"},

    --SMGS--
    ["324215364"] = {"Micro SMG","https://i.imgur.com/pX69qri.png"},
    ["736523883"] = {"SMG","https://i.imgur.com/Yaw6e5j.png"},
    ["-270015777"] = {"Asssault SMG","https://i.imgur.com/oj8SEiq.png"},
    ["-1121678507"] = {"Mini SMG","https://i.imgur.com/8j8O6Vk.png"},
    ["2024373456"] = {"SMG MK2","https://i.imgur.com/c6WgThi.png"},
    ["-619010992"] = {"Machinepistol","https://i.imgur.com/EQhKVFA.png"},
    ["171789620"] = {"CombatPDW","https://i.imgur.com/Aho6Gds.png"},

    --SHOTGUNS--
    ["487013001"] = {"Pump Shotgun","https://i.imgur.com/fJHjfRJ.png"},
    ["2017895192"] = {"Sawn Off Shotgun","https://i.imgur.com/2BHjwN3.png"},
    ["-494615257"] = {"Assault Shotgun","https://i.imgur.com/W6n8vV1.png"},
    ["-1654528753"] = {"Bullpup Shotgun","https://i.imgur.com/Gx51rXE.png"},
    ["1432025498"] = {"Pump Shotgun MK2","https://i.imgur.com/C1iD5jJ.png"},
    ["984333226"] = {"Heavy Shotgun","https://i.imgur.com/QtbzLWe.png"},

    --RIFLES--
    ["-1074790547"] = {"Assault Rifle","https://i.imgur.com/zo4aNps.png"},
    ["-2084633992"] = {"Carbine Rifle","https://i.imgur.com/aRhoCMI.png"},
    ["-1357824103"] = {"Advanced Rifle","https://i.imgur.com/a1iYUdf.png"},
    ["-1063057011"] = {"Special Carbine","https://i.imgur.com/3h70W8F.png"},
    ["2132975508"] = {"Bullpup Rifle","https://i.imgur.com/b08T8Lt.png"},
    ["-2066285827"] = {"Bullpup Rifle MK2","https://i.imgur.com/jDQxYYH.png"},
    ["-1768145561"] = {"Special Carbine MK2","https://i.imgur.com/P8Ks1xl.png"},
    ["961495388"] = {"Assault Rifle MK2","https://i.imgur.com/4mUv1bK.png"},
    ["-86904375"] = {"Carbine Rifle MK2","https://i.imgur.com/2N6YFmh.png"},
    ["1649403952"] = {"Compact Rifle","https://i.imgur.com/JiUpji1.png"},

    --MACHINE GUNS--
    ["-1660422300"] = {"Maskingevær","https://i.imgur.com/fBF3PkM.png"},
    ["2144741730"] = {"Combat MG","https://i.imgur.com/DvRTu2x.png"},
    ["3686625920"] = {"Maskingevær MK2","https://i.imgur.com/ZGtt7PB.png"},
    ["1627465347"] = {"Gusenberg","https://i.imgur.com/QblizuA.png"},

    --SNIPER RIFLES--
    ["100416529"] = {"Sniper","https://i.imgur.com/GPwI2HZ.png"},
    ["205991906"] = {"Heavy Sniper","https://i.imgur.com/aFK6DWB.png"},
    ["1785463520"] = {"Marksman Rifle MK2","https://i.imgur.com/PVuvUtY.png"},
    ["177293209"] = {"Heavy Sniper MK2","https://i.imgur.com/Q0Sk4ds.png"},
    ["-952879014"] = {"Marksman Rifle","https://i.imgur.com/uGrz4gn.png"},

    --HEAVY WEAPONS--
    ["-1568386805"] = {"Grenade Launcher","https://i.imgur.com/g0AMvbH.png"}
}

return Config
